version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - '8000:8000'
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:11.3.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.2.0
    ports:
      - "3100:3100"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node  # настройка для запуска одной ноды (полезно для разработки)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Параметры Java, выделяющие 512MB памяти
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
