# Generated by Django 5.1.3 on 2024-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
